name: qiskit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - matplotlib
  - seaborn
  - pylatexenc
  - sympy
  - qiskit
  - qiskit-aer
  - qiskit-ibm-runtime
  - qiskit-ibm-provider
  - qiskit-algorithms
  - python-dotenv
